### ISSUE TITLE
关于解析后无法通过域名来访问指向的网页

### ISSUE THREAD

**Issue by kkshell** [Wensibob/Wensibob.github.io#1]
按照你的博客的买了域名之后进行解析  然后我将所有的解析都删除了，然后按照你的博客那些的添加两个CNAME并且将主机记录改为@和www，记录值也修改为我对应的kkshell.github.io   还有在根目录下也添加了CNAME的文件写上了我的域名   但是还是不行

**Comment by kkshell** [comment]
还有我在本地添加的CNAME不能deploy到github里  只能在github里create file添加。。

**Comment by Wensibob** [comment]
我尝试登录你的网站：https://kkshell.github.io ，发现可以直接重定向到你的域名：http://kkshell.top/  只是显示DNS解析错误，可能是你在域名解析的时候出现了问题，你可以再尝试修改一下。

**Comment by Wensibob** [comment]
记住，域名解析中只是添加两条新的解析，而不是把默认的解析删除了只剩下这两条解析，解析成功后会隔几分钟生效，可以清楚一下浏览器的缓存，之后在你的github项目中的settings页面可以看到有类似如下的成功提示，就说明解析成功了。
![成功提示界面](https://cloud.githubusercontent.com/assets/24890876/25192792/39a1de16-24fa-11e7-869a-5a469770fe7e.png)

**Comment by kkshell** [comment]
那如果我把之前的都删除了只剩下新添加的那两个那怎么办？

**Comment by kkshell** [comment]
还有我买的第一个域名是一进去解析就有五六条解析记录，第二个域名一进去什么都没有我只是添加了两条，但是怎么两个都不能访问。。

**Comment by kkshell** [comment]
好了 解决了  我还要在域名解析那添加一条*记录的默认主机记录  记录值为myname.github.io就可以了   谢谢
