### ISSUE TITLE
站点图标问题？

### ISSUE THREAD

**Issue by baowenqing** [Wensibob/Wensibob.github.io#12]
站点图标显示不了，一直都是浏览器的默认图标
目前在本地更新了文章发布正常

**Comment by Wensibob** [comment]
你说的是网站标签页中的logo图标对吧，官方文档中是要求将图标文件放置在`blog/img/`文件夹下，并且命名为`favicon.ico`，修改之后重新刷新页面，如果仍然没有生效那就重新服务器
