### ISSUE TITLE
在搭建hexo时 hexo g的问题

### ISSUE THREAD

**Issue by bizymusic** [Wensibob/Wensibob.github.io#2]
老哥在吗 我看了你的创建hexo 
hexo generate 
hexo server
在做到这一步的时候 ，会出现如下代码，这是为什么啊   在做hexo s也是这些代码
λ hexo generate
Usage: hexo <command>

Commands:
help Get help on a command.
init Create a new Hexo folder.
version Display version information.

Global Options:
--config Specify config file instead of using _config.yml
--cwd Specify the CWD
--debug Display all verbose messages in the terminal
--draft Display draft posts
--safe Disable all plugins and scripts
--silent Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

**Comment by Wensibob** [comment]
描述具体到哪一步，贴上报错的截图，另外确定是否安装最新版的node以及hexo

**Comment by bizymusic** [comment]
是最新的node啊  就是做到 hexo generate这一步
![qq 20170421105009](https://cloud.githubusercontent.com/assets/27797182/25260686/843b552e-2680-11e7-9b67-ff259ea311fc.png)

**Comment by bizymusic** [comment]
哈哈哈 知道那里的问题了  我没在 我创建的文件blog里启动命令行 现在可以了  谢了哈
