### ISSUE TITLE
建站问题

### ISSUE THREAD

**Issue by kkshell** [Wensibob/Wensibob.github.io#3]
想问下在电脑本地创建的CNAME不能通过hexo g 和hexo d 来进行上传的吗？只能通过在github中create file？

**Comment by Wensibob** [comment]
准确来说 CNAME 文件是放在 hexo 项目下的 source 目录，你再运行下
```
hexo g
```
然后你再去 public 目录中看看就会发现新增了这个文件，接着再使用
```
hexo d
```
这样就可以将public文件夹里面的内容同步到github，确切来说，github上面的代码就是public文件夹里面的代码
