### ISSUE TITLE
参照教程一步步走来,卡在了域名解析,其余Issues已经读完

### ISSUE THREAD

**Issue by RedWolfChao** [Wensibob/Wensibob.github.io#7]
显示"尊敬的用户，您好
很抱歉，该网站暂时无法访问，可能由以下原因导致：
原因一：未备案或未接入；根据《非经营性互联网信息服务备案管理办法》，网站需要完成备案或接入。请登录代备案管理平台进行操作。
原因二：网站内容与备案信息不符或备案信息不准确；根据《非经营性互联网信息服务备案管理办法》，网站内容需要与备案信息一致，且备案信息需真实有效。建议网站管理员尽快修改网站信息。"

github部分gitPage一直没有变化.没有变成我的域名,其次 在解析中我添加了默认的*以及海外的www和@,都不行,不知道老铁们是不是遇到过同样的情况.

**Comment by Wensibob** [comment]
在没有进行域名解析的时候，访问github page是否可行？
另外请将错误信息描述详细，可以适当加截图。

**Comment by RedWolfChao** [comment]
无奈截图如下,无论我解析域名还是不解析域名 用过github page是可行的,因为gitpaga一直没有变化过,一直都是github.xx.io

![4000](http://img.blog.csdn.net/20170425093059940?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvUmVkV29sZkNoYW8=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

![github](http://img.blog.csdn.net/20170425093113581?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvUmVkV29sZkNoYW8=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

![解析](http://img.blog.csdn.net/20170425093129501?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvUmVkV29sZkNoYW8=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

![备案](http://img.blog.csdn.net/20170425093142128?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvUmVkV29sZkNoYW8=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by Wensibob** [comment]
可以尝试[#1](https://github.com/Wensibob/Wensibob.github.io/issues/1)

**Comment by RedWolfChao** [comment]
万分抱歉,我这边找到问题了.需要备案的不是买的域名而是买的服务器站点,我把关联的服务器站点关闭了,就不用备案了,还是报404问题,我去#1 看看 谢谢了
