### ISSUE TITLE
favicon应该放在什么路径下呢？

### ISSUE THREAD

**Issue by stay4cold** [Wensibob/Wensibob.github.io#8]

**Comment by Wensibob** [comment]
理论上来说放在public文件夹的任何位置都是可以的，例如我的是放在：`blog/public/img`文件夹下，因此在`blog/themes/indigo/_config.yml`配置文件中 应该这样配置：
```
# favicon
favicon: /img/favicon.ico
```

**Comment by stay4cold** [comment]
@Wensibob 好的，已经解决，感谢
