### ISSUE TITLE
打扰了，向您请教一个问题

### ISSUE THREAD

**Issue by LeiHolmes** [Wensibob/Wensibob.github.io#9]
你好，看了你关于hexo的博客，很有帮助！谢谢，就是到最后一步我遇到个问题想向你咨询下：我也在阿里云买好了域名，但是设置好解析后并不能通过我申请的域名访问我的博客。我看域名状态是在审核中，有可能是因为这个吗？

**Comment by Wensibob** [comment]
域名需要审核通过之后才可以正常访问。
